// Generated by CoffeeScript 1.9.3
module.exports.testApiLoginUnprocessableNoBody = function(command_serve, shutdown, envStringBaseUrl, urlApiLogin, requestPromise) {
  return function(test) {
    return command_serve('cockpit').then(function() {
      return requestPromise({
        method: 'POST',
        url: envStringBaseUrl + urlApiLogin(),
        json: true
      });
    }).then(function(arg) {
      var response;
      response = arg[0];
      test.equal(response.statusCode, 422);
      test.deepEqual(response.body, {
        username: 'must not be null or undefined',
        password: 'must not be null or undefined'
      });
      return shutdown();
    }).then(function() {
      return test.done();
    });
  };
};

module.exports.testApiLoginUnprocessableInvalidPassword = function(command_serve, shutdown, envStringBaseUrl, urlApiLogin, requestPromise) {
  return function(test) {
    return command_serve('cockpit').then(function() {
      return requestPromise({
        method: 'POST',
        url: envStringBaseUrl + urlApiLogin(),
        json: true,
        body: {
          username: 'exampleuser',
          password: 'open'
        }
      });
    }).then(function(arg) {
      var response;
      response = arg[0];
      test.equal(response.statusCode, 422);
      test.deepEqual(response.body, {
        password: 'must be at least 8 characters long'
      });
      return shutdown();
    }).then(function() {
      return test.done();
    });
  };
};

module.exports.testApiLoginUnprocessableUserNotFound = function(command_serve, pgDropCreateMigrate, shutdown, envStringBaseUrl, urlApiLogin, requestPromise) {
  return function(test) {
    return pgDropCreateMigrate().then(function() {
      return command_serve('cockpit');
    }).then(function() {
      return requestPromise({
        method: 'POST',
        url: envStringBaseUrl + urlApiLogin(),
        json: true,
        body: {
          username: 'exampleuser',
          password: 'opensesame'
        }
      });
    }).then(function(arg) {
      var response;
      response = arg[0];
      test.equal(response.statusCode, 422);
      test.deepEqual(response.body, 'invalid username or password');
      return shutdown();
    }).then(function() {
      return test.done();
    });
  };
};

module.exports.testApiLoginUnprocessableWrongPassword = function(command_serve, pgDropCreateMigrate, shutdown, envStringBaseUrl, urlApiLogin, requestPromise, insertUser) {
  return function(test) {
    return pgDropCreateMigrate().then(function() {
      return insertUser({
        email: 'test@example.com',
        name: 'exampleuser',
        password: 'topsecret',
        rights: ''
      });
    }).then(function() {
      return command_serve('cockpit');
    }).then(function() {
      return requestPromise({
        method: 'POST',
        url: envStringBaseUrl + urlApiLogin(),
        json: true,
        body: {
          username: 'test@example.com',
          password: 'opensesame'
        }
      });
    }).then(function(arg) {
      var response;
      response = arg[0];
      test.equal(response.statusCode, 422);
      test.deepEqual(response.body, 'invalid username or password');
      return shutdown();
    }).then(function() {
      return test.done();
    });
  };
};

module.exports.testApiLoginOk = function(command_serve, pgDropCreateMigrate, shutdown, envStringBaseUrl, urlApiLogin, requestPromise, insertUser) {
  return function(test) {
    return pgDropCreateMigrate().then(function() {
      return insertUser({
        email: 'test@example.com',
        name: 'exampleuser',
        password: 'topsecret',
        rights: ''
      });
    }).then(function() {
      return command_serve('cockpit');
    }).then(function() {
      return requestPromise({
        method: 'POST',
        url: envStringBaseUrl + urlApiLogin(),
        json: true,
        body: {
          username: 'test@example.com',
          password: 'topsecret'
        }
      });
    }).then(function(arg) {
      var response, token;
      response = arg[0];
      test.equal(response.statusCode, 200);
      token = response.body.token;
      test.ok(token != null);
      test.equal(response.body.user.email, 'test@example.com');
      test.equal(response.body.user.name, 'exampleuser');
      test.equal(response.body.user.rights, '');
      test.ok(response.body.user.password == null);
      return requestPromise({
        method: 'POST',
        url: envStringBaseUrl + urlApiLogin(),
        json: true,
        body: {
          username: 'exampleuser',
          password: 'topsecret'
        }
      });
    }).then(function(arg) {
      var response, token;
      response = arg[0];
      test.equal(response.statusCode, 200);
      token = response.body.token;
      test.ok(token != null);
      test.equal(response.body.user.email, 'test@example.com');
      test.equal(response.body.user.name, 'exampleuser');
      test.equal(response.body.user.rights, '');
      test.ok(response.body.user.password == null);
      return shutdown();
    }).then(function() {
      return test.done();
    });
  };
};
