language: node_js
node_js:
    - "0.12"
    - "iojs-2"
    - "iojs-3"
    - "4.0"
script: npm run $NPM_COMMAND
sudo: false
env:
  global:
    - CXX=g++-4.8
    - PORT=8080
    - BASE_URL="http://localhost:$PORT"
    - STATIC_PATH="static"
    - MIGRATION_PATH="migrations"
    - POSTGRES_DATABASE='fragments_user'
    - DATABASE_URL="postgres://localhost:5432/$POSTGRES_DATABASE"
    - POSTGRES_POOL_SIZE=40
    - BCRYPT_COST=10
    - JWT_ENCRYPTION_PASSWORD='super secret jwt encryption password'
    - JWT_SIGNING_SECRET='super secret jwt signing secret'
  matrix:
    - NPM_COMMAND=test
    - NPM_COMMAND=test-with-coverage
addons:
  postgresql: "9.4"
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
matrix:
  exclude:
    # don't collect code coverage more than once
    - node_js: "iojs-2"
      env: NPM_COMMAND=test-with-coverage
    - node_js: "iojs-3"
      env: NPM_COMMAND=test-with-coverage
    - node_js: "4.0"
      env: NPM_COMMAND=test-with-coverage
    # don't test 0.12 more than once
    - node_js: "0.12"
      env: NPM_COMMAND=test
