// Generated by CoffeeScript 1.9.2
module.exports.rightsStringToRightsArray = function() {
  return function(string) {
    return string.split('\n').map(function(x) {
      return x.trim();
    }).filter(function(x) {
      return x !== '';
    }).filter(function(x) {
      return x.charAt(0) !== '#';
    });
  };
};

module.exports.rightsArrayToRightsObject = function() {
  return function(array) {
    var result;
    result = {};
    array.forEach(function(x) {
      return result[x] = true;
    });
    return result;
  };
};

module.exports.rightsStringToRightsObject = function(rightsStringToRightsArray, rightsArrayToRightsObject) {
  return function(string) {
    return rightsArrayToRightsObject(rightsStringToRightsArray(string));
  };
};
