// Generated by CoffeeScript 1.9.2
module.exports.omitPassword = function(_) {
  var omitPassword;
  omitPassword = function(userOrUsers) {
    if (Array.isArray(userOrUsers)) {
      return _.map(userOrUsers, omitPassword);
    } else {
      return _.omit(userOrUsers, 'password');
    }
  };
  return omitPassword;
};

module.exports.insertUser = function(userTable, hashPasswordIfPresent) {
  return function(user) {
    return userTable.queueBeforeEach(hashPasswordIfPresent).allow('password', 'email', 'name', 'created_at', 'rights').returnFirst().insert(user);
  };
};

module.exports.firstUserWhereLogin = function(userTable, comparePasswordToHashed) {
  return function(login) {
    return userTable.where({
      $or: [
        {
          email: login.username
        }, {
          name: login.username
        }
      ]
    }).first().then(function(user) {
      if (user == null) {
        return null;
      }
      return comparePasswordToHashed(login.password, user.password).then(function(isEqual) {
        if (isEqual) {
          return user;
        } else {
          return null;
        }
      });
    });
  };
};

module.exports.firstUserWhereNameAndNotId = function(userTable) {
  return function(name, id) {
    return userTable.where({
      name: name,
      id: {
        $ne: id
      }
    }).first();
  };
};

module.exports.firstUserWhereEmailAndNotId = function(userTable) {
  return function(email, id) {
    return userTable.where({
      email: email,
      id: {
        $ne: id
      }
    }).first();
  };
};

module.exports.updateUserWhereId = function(userTable, hashPasswordIfPresent) {
  return function(user, id) {
    return userTable.queueBeforeEach(hashPasswordIfPresent).allow('password', 'email', 'name', 'rights').where({
      id: id
    }).returnFirst().update(user);
  };
};

module.exports.grantUserRightWhereId = function(userTable, mesa) {
  return function(right, id) {
    return userTable.where({
      id: id
    }).where("rights NOT LIKE '%' || ? || '%'", right).returnFirst().unsafe().update({
      rights: mesa.raw("rights || '\n' || ?", right)
    });
  };
};

module.exports.revokeUserRightWhereId = function(userTable, mesa) {
  return function(right, id) {
    return userTable.where({
      id: id
    }).where("rights LIKE '%' || ? || '%'", right).returnFirst().unsafe().update({
      rights: mesa.raw("replace(rights, ?, '')", right)
    });
  };
};
