// Generated by CoffeeScript 1.9.3
module.exports.apiLogin = function(POST, urlApiLogin, newJwt, loginValidator, firstUserWhereLogin, _) {
  return POST(urlApiLogin(), function(body, endUnprocessableJSON, endUnprocessableText, endJSON) {
    var errors;
    errors = loginValidator(body);
    if (errors != null) {
      endUnprocessableJSON(errors);
      return;
    }
    return firstUserWhereLogin(body).then(function(user) {
      var token;
      if (user == null) {
        endUnprocessableText('invalid username or password');
        return;
      }
      token = newJwt({
        id: user.id
      });
      return endJSON({
        token: token,
        user: _.omit(user, 'password')
      });
    });
  });
};
