// Generated by CoffeeScript 1.9.2
module.exports.cockpitAccessControlMiddleware = function(MIDDLEWARE) {
  return MIDDLEWARE(function(matchCurrentUrl, urlCockpitApi, canAccessCockpit, endForbidden, next) {
    if (matchCurrentUrl(urlCockpitApi('*')) && !canAccessCockpit()) {
      return endForbidden();
    } else {
      return next();
    }
  });
};

module.exports.cockpit = function(sequenz, MIDDLEWARE, commonMiddlewarePrelude, cockpitAccessControlMiddleware, route_cockpitApiLogin, route_cockpitApiMe, route_cockpitApiUsers) {
  return sequenz([
    commonMiddlewarePrelude, route_cockpitApiLogin, cockpitAccessControlMiddleware, route_cockpitApiMe, route_cockpitApiUsers, MIDDLEWARE(function(end404) {
      return end404();
    })
  ]);
};
