// Generated by CoffeeScript 1.9.3
module.exports.cockpitAccessControlMiddleware = function(MIDDLEWARE) {
  return MIDDLEWARE(function(matchCurrentUrl, urlApi, canAccessCockpit, endForbidden, next) {
    if (matchCurrentUrl(urlApi('*')) && !canAccessCockpit()) {
      return endForbidden();
    } else {
      return next();
    }
  });
};

module.exports.cockpit = function(sequenz, MIDDLEWARE, commonMiddlewarePrelude, cockpitAccessControlMiddleware, apiLogin, apiCurrentUserGet, apiCurrentUserPatch, apiUsersGet, apiUsersPost, apiUserGet, apiUserPatch, apiUserDelete) {
  return sequenz([
    commonMiddlewarePrelude, apiLogin, cockpitAccessControlMiddleware, apiCurrentUserGet, apiCurrentUserPatch, apiUsersGet, apiUsersPost, apiUserGet, apiUserPatch, apiUserDelete, MIDDLEWARE(function(end404) {
      return end404();
    })
  ]);
};
