// Generated by CoffeeScript 1.9.3
module.exports.requestPromise = function(Promise, request) {
  return Promise.promisify(request);
};

module.exports.faker = function() {
  return require('faker');
};

module.exports.siv = function() {
  return require('siv');
};
