// Generated by CoffeeScript 1.9.3
module.exports.flexibleUrl = function() {
  return function(prefix) {
    return function(suffix) {
      if (suffix) {
        return prefix + '/' + suffix;
      } else {
        return prefix;
      }
    };
  };
};

module.exports.urlCockpitApi = function(flexibleUrl) {
  return flexibleUrl('/api/cockpit');
};

module.exports.urlCockpitApiLogin = function(urlCockpitApi) {
  return function() {
    return urlCockpitApi('login');
  };
};

module.exports.urlCockpitApiMe = function(urlCockpitApi) {
  return function() {
    return urlCockpitApi('me');
  };
};

module.exports.urlCockpitApiUsers = function(flexibleUrl, urlCockpitApi) {
  return flexibleUrl(urlCockpitApi('users'));
};

module.exports.urlCockpit = function(flexibleUrl) {
  return flexibleUrl('/cockpit');
};

module.exports.urlPatternCockpit = function(Pattern, urlCockpit) {
  return new Pattern(urlCockpit());
};
