var hinoki, rightsSource,
  slice = [].slice;

hinoki = require('hinoki');

rightsSource = function(key) {
  var factory, prefix;
  prefix = 'fragments_can';
  if ((0 === key.indexOf(prefix)) && (key.length > prefix.length)) {
    factory = function(currentUserHasRight) {
      return function() {
        var args;
        args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
        return currentUserHasRight.apply(null, [key.slice(prefix.length - 3)].concat(slice.call(args)));
      };
    };
    factory.__source = 'generated by fragments-user';
    return factory;
  }
};

module.exports = hinoki.source([__dirname + '/factories', rightsSource]);
