// Generated by CoffeeScript 1.9.2
var slice = [].slice;

module.exports.currentUser = function(token, firstUserWhereId, _) {
  var id;
  id = token != null ? token.id : void 0;
  if (id == null) {
    return null;
  }
  return firstUserWhereId(id).then(function(user) {
    if (user == null) {
      return null;
    }
    return _.omit(user, 'password');
  });
};

module.exports.currentRightsArray = function(currentUser, rightsStringToRightsArray) {
  if (currentUser == null) {
    return [];
  }
  return rightsStringToRightsArray(currentUser.rights);
};

module.exports.currentRightsObject = function(currentUser, rightsStringToRightsObject) {
  if (currentUser == null) {
    return {};
  }
  return rightsStringToRightsObject(currentUser.rights);
};

module.exports.currentUserHasRight = function(currentRightsObject, isjs, _) {
  return function() {
    var args, filteredArgs, result, right;
    right = arguments[0], args = 2 <= arguments.length ? slice.call(arguments, 1) : [];
    filteredArgs = _.filter(args, isjs.not.undefined);
    result = filteredArgs.length === 0 ? (currentRightsObject[right] != null) || (currentRightsObject[right + '()'] != null) : currentRightsObject[right + '(' + filteredArgs.join(',') + ')'] != null;
    return result;
  };
};

module.exports.canAccessCockpit = function(currentUserHasRight) {
  return function() {
    return currentUserHasRight('canAccessCockpit');
  };
};

module.exports.canReadUsers = function(currentUserHasRight) {
  return function(id) {
    return currentUserHasRight('canReadUsers', id);
  };
};

module.exports.canCreateUsers = function(currentUserHasRight) {
  return function() {
    return currentUserHasRight('canCreateUsers');
  };
};

module.exports.canUpdateUsers = function(currentUserHasRight) {
  return function(id) {
    return currentUserHasRight('canUpdateUsers', id);
  };
};

module.exports.canDeleteUsers = function(currentUserHasRight) {
  return function(id) {
    return currentUserHasRight('canDeleteUsers', id);
  };
};
